/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { X_TOKEN_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const BUY_TOKENS_DISCRIMINATOR = 1;

export function getBuyTokensDiscriminatorBytes() {
  return getU8Encoder().encode(BUY_TOKENS_DISCRIMINATOR);
}

export type BuyTokensInstruction<
  TProgram extends string = typeof X_TOKEN_PROGRAM_ADDRESS,
  TAccountBuyer extends string | AccountMeta<string> = string,
  TAccountBondingCurve extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountBuyerTokenAccount extends string | AccountMeta<string> = string,
  TAccountFeeRecipient extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends
    | string
    | AccountMeta<string> = 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountBuyer extends string
        ? WritableSignerAccount<TAccountBuyer> &
            AccountSignerMeta<TAccountBuyer>
        : TAccountBuyer,
      TAccountBondingCurve extends string
        ? WritableAccount<TAccountBondingCurve>
        : TAccountBondingCurve,
      TAccountMint extends string
        ? WritableAccount<TAccountMint>
        : TAccountMint,
      TAccountBuyerTokenAccount extends string
        ? WritableAccount<TAccountBuyerTokenAccount>
        : TAccountBuyerTokenAccount,
      TAccountFeeRecipient extends string
        ? WritableAccount<TAccountFeeRecipient>
        : TAccountFeeRecipient,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type BuyTokensInstructionData = {
  discriminator: number;
  /** Amount of tokens to buy */
  tokenAmount: bigint;
  /** Maximum SOL amount willing to pay (slippage protection) */
  maxSolAmount: bigint;
};

export type BuyTokensInstructionDataArgs = {
  /** Amount of tokens to buy */
  tokenAmount: number | bigint;
  /** Maximum SOL amount willing to pay (slippage protection) */
  maxSolAmount: number | bigint;
};

export function getBuyTokensInstructionDataEncoder(): FixedSizeEncoder<BuyTokensInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['tokenAmount', getU64Encoder()],
      ['maxSolAmount', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: 1 }),
  );
}

export function getBuyTokensInstructionDataDecoder(): FixedSizeDecoder<BuyTokensInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['tokenAmount', getU64Decoder()],
    ['maxSolAmount', getU64Decoder()],
  ]);
}

export function getBuyTokensInstructionDataCodec(): FixedSizeCodec<
  BuyTokensInstructionDataArgs,
  BuyTokensInstructionData
> {
  return combineCodec(
    getBuyTokensInstructionDataEncoder(),
    getBuyTokensInstructionDataDecoder(),
  );
}

export type BuyTokensInput<
  TAccountBuyer extends string = string,
  TAccountBondingCurve extends string = string,
  TAccountMint extends string = string,
  TAccountBuyerTokenAccount extends string = string,
  TAccountFeeRecipient extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
> = {
  /** Buyer account */
  buyer: TransactionSigner<TAccountBuyer>;
  /** Bonding curve state account */
  bondingCurve: Address<TAccountBondingCurve>;
  /** Token mint account */
  mint: Address<TAccountMint>;
  /** Buyer's token account (will be created if doesn't exist) */
  buyerTokenAccount: Address<TAccountBuyerTokenAccount>;
  /** Fee recipient account */
  feeRecipient: Address<TAccountFeeRecipient>;
  /** System Program */
  systemProgram?: Address<TAccountSystemProgram>;
  /** Token Program */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** Associated Token Program */
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  tokenAmount: BuyTokensInstructionDataArgs['tokenAmount'];
  maxSolAmount: BuyTokensInstructionDataArgs['maxSolAmount'];
};

export function getBuyTokensInstruction<
  TAccountBuyer extends string,
  TAccountBondingCurve extends string,
  TAccountMint extends string,
  TAccountBuyerTokenAccount extends string,
  TAccountFeeRecipient extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TProgramAddress extends Address = typeof X_TOKEN_PROGRAM_ADDRESS,
>(
  input: BuyTokensInput<
    TAccountBuyer,
    TAccountBondingCurve,
    TAccountMint,
    TAccountBuyerTokenAccount,
    TAccountFeeRecipient,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): BuyTokensInstruction<
  TProgramAddress,
  TAccountBuyer,
  TAccountBondingCurve,
  TAccountMint,
  TAccountBuyerTokenAccount,
  TAccountFeeRecipient,
  TAccountSystemProgram,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? X_TOKEN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    buyer: { value: input.buyer ?? null, isWritable: true },
    bondingCurve: { value: input.bondingCurve ?? null, isWritable: true },
    mint: { value: input.mint ?? null, isWritable: true },
    buyerTokenAccount: {
      value: input.buyerTokenAccount ?? null,
      isWritable: true,
    },
    feeRecipient: { value: input.feeRecipient ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.buyer),
      getAccountMeta(accounts.bondingCurve),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.buyerTokenAccount),
      getAccountMeta(accounts.feeRecipient),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
    ],
    programAddress,
    data: getBuyTokensInstructionDataEncoder().encode(
      args as BuyTokensInstructionDataArgs,
    ),
  } as BuyTokensInstruction<
    TProgramAddress,
    TAccountBuyer,
    TAccountBondingCurve,
    TAccountMint,
    TAccountBuyerTokenAccount,
    TAccountFeeRecipient,
    TAccountSystemProgram,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram
  >;

  return instruction;
}

export type ParsedBuyTokensInstruction<
  TProgram extends string = typeof X_TOKEN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Buyer account */
    buyer: TAccountMetas[0];
    /** Bonding curve state account */
    bondingCurve: TAccountMetas[1];
    /** Token mint account */
    mint: TAccountMetas[2];
    /** Buyer's token account (will be created if doesn't exist) */
    buyerTokenAccount: TAccountMetas[3];
    /** Fee recipient account */
    feeRecipient: TAccountMetas[4];
    /** System Program */
    systemProgram: TAccountMetas[5];
    /** Token Program */
    tokenProgram: TAccountMetas[6];
    /** Associated Token Program */
    associatedTokenProgram: TAccountMetas[7];
  };
  data: BuyTokensInstructionData;
};

export function parseBuyTokensInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedBuyTokensInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      buyer: getNextAccount(),
      bondingCurve: getNextAccount(),
      mint: getNextAccount(),
      buyerTokenAccount: getNextAccount(),
      feeRecipient: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
    },
    data: getBuyTokensInstructionDataDecoder().decode(instruction.data),
  };
}
