/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Encoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/kit';
import { X_TOKEN_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const WITHDRAW_RESERVES_DISCRIMINATOR = 3;

export function getWithdrawReservesDiscriminatorBytes() {
  return getU8Encoder().encode(WITHDRAW_RESERVES_DISCRIMINATOR);
}

export type WithdrawReservesInstruction<
  TProgram extends string = typeof X_TOKEN_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountBondingCurve extends string | AccountMeta<string> = string,
  TAccountMint extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountRecipient extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountBondingCurve extends string
        ? ReadonlyAccount<TAccountBondingCurve>
        : TAccountBondingCurve,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountRecipient extends string
        ? WritableAccount<TAccountRecipient>
        : TAccountRecipient,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type WithdrawReservesInstructionData = {
  /** 0 = withdraw all, otherwise exact lamports to withdraw */
  lamports: bigint;
};

export type WithdrawReservesInstructionDataArgs = {
  /** 0 = withdraw all, otherwise exact lamports to withdraw */
  lamports: number | bigint;
};

export function getWithdrawReservesInstructionDataEncoder(): FixedSizeEncoder<WithdrawReservesInstructionDataArgs> {
  return getStructEncoder([['lamports', getU64Encoder()]]);
}

export function getWithdrawReservesInstructionDataDecoder(): FixedSizeDecoder<WithdrawReservesInstructionData> {
  return getStructDecoder([['lamports', getU64Decoder()]]);
}

export function getWithdrawReservesInstructionDataCodec(): FixedSizeCodec<
  WithdrawReservesInstructionDataArgs,
  WithdrawReservesInstructionData
> {
  return combineCodec(
    getWithdrawReservesInstructionDataEncoder(),
    getWithdrawReservesInstructionDataDecoder(),
  );
}

export type WithdrawReservesInput<
  TAccountAuthority extends string = string,
  TAccountBondingCurve extends string = string,
  TAccountMint extends string = string,
  TAccountTreasury extends string = string,
  TAccountRecipient extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Authority that controls the bonding curve */
  authority: TransactionSigner<TAccountAuthority>;
  /** Bonding curve state account (PDA) */
  bondingCurve: Address<TAccountBondingCurve>;
  /** Token mint account */
  mint: Address<TAccountMint>;
  /** Treasury PDA (system-owned) holding SOL reserves */
  treasury: Address<TAccountTreasury>;
  /** Recipient wallet to receive lamports */
  recipient: Address<TAccountRecipient>;
  /** System Program */
  systemProgram?: Address<TAccountSystemProgram>;
  lamports: WithdrawReservesInstructionDataArgs['lamports'];
};

export function getWithdrawReservesInstruction<
  TAccountAuthority extends string,
  TAccountBondingCurve extends string,
  TAccountMint extends string,
  TAccountTreasury extends string,
  TAccountRecipient extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof X_TOKEN_PROGRAM_ADDRESS,
>(
  input: WithdrawReservesInput<
    TAccountAuthority,
    TAccountBondingCurve,
    TAccountMint,
    TAccountTreasury,
    TAccountRecipient,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): WithdrawReservesInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountBondingCurve,
  TAccountMint,
  TAccountTreasury,
  TAccountRecipient,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? X_TOKEN_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    bondingCurve: { value: input.bondingCurve ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: true },
    recipient: { value: input.recipient ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.bondingCurve),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.recipient),
      getAccountMeta(accounts.systemProgram),
    ],
    programAddress,
    data: getWithdrawReservesInstructionDataEncoder().encode(
      args as WithdrawReservesInstructionDataArgs,
    ),
  } as WithdrawReservesInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountBondingCurve,
    TAccountMint,
    TAccountTreasury,
    TAccountRecipient,
    TAccountSystemProgram
  >;

  return instruction;
}

export type ParsedWithdrawReservesInstruction<
  TProgram extends string = typeof X_TOKEN_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Authority that controls the bonding curve */
    authority: TAccountMetas[0];
    /** Bonding curve state account (PDA) */
    bondingCurve: TAccountMetas[1];
    /** Token mint account */
    mint: TAccountMetas[2];
    /** Treasury PDA (system-owned) holding SOL reserves */
    treasury: TAccountMetas[3];
    /** Recipient wallet to receive lamports */
    recipient: TAccountMetas[4];
    /** System Program */
    systemProgram: TAccountMetas[5];
  };
  data: WithdrawReservesInstructionData;
};

export function parseWithdrawReservesInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedWithdrawReservesInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      bondingCurve: getNextAccount(),
      mint: getNextAccount(),
      treasury: getNextAccount(),
      recipient: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getWithdrawReservesInstructionDataDecoder().decode(instruction.data),
  };
}
